# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Contemplative Neuroscience"
description: >
   Reviewing Papers on Meditative States and Their Neurological Signatures


logo: "/assets/images/logo_sm.png"
float_logo: false # Adds a floating little logo to the top left of the screen.

# blog cover
cover: "/assets/images/index_header.jpg"

name: 'Craig Booth'
author: 'Craig Booth'
author_image: "/assets/images/logo_sm.png"

paginate:	5

menu_items:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: What Is Contemplative Neuroscience?
    url: /what-is-contemplative-neuroscience/

url: "https://contemplativeneuroscience.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@cmb'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

permalink: /:title/

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cmb
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
