plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Contemplative Neuroscience"
description: >
   Reviewing Papers on Meditative States and Their Neurological Signatures


logo: "/assets/images/logo_sm.png"
float_logo: false # Adds a floating little logo to the top left of the screen.

# blog cover
cover: "/assets/images/index_header.jpg"

name: 'Craig Booth'
author: 'Craig Booth'
author_image: "/assets/images/logo_sm.png"

paginate:	5

menu_items:
  - title: Home
    url: /
  - title: Research Themes
    url: /themes/
  - title: All Papers
    url: /all-papers/
  - title: Glossary
    url: /glossary/
  - title: About
    url: /about/

url: "https://contemplativeneuroscience.com" # the base hostname & protocol for your site
baseurl: ""

#used to display twitter cards
twitter_handle: '@cmb'

#google_analytics: UA-XXXXX-X

permalink: /:title/

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cmb
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
